export const make_projects = [
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_1.jpg",
    name: "full project",
    label: "Designer",
    owner: "Alice",
    date: "15 May 25 ",
    status: "Published",
    tool: ["Image Tracking", "Face Tracking", "World Tracking"],
    link: "https://example.com/project1",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_2.jpg",
    name: "Untitled project",
    label: "Designer legacy",
    owner: "Alice",
    date: "3 Mar 25 ",
    status: "Published",
    tool: [],
    link: "https://example.com/project2",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_3.jpg",
    name: "Image Tracking",
    label: "Designer legacy",
    owner: "John",
    date: "24 Dec 24",
    status: "Published",
    tool: ["Image Tracking"],
    link: "https://example.com/project3",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_4.jpg",
    name: "Face Tracking",
    label: "Designer legacy",
    owner: "Tony",
    date: "2 Nov 24",
    status: "Unpublished",
    tool: ["Face Tracking"],
    link: "https://example.com/project4",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_5.jpg",
    name: "world tracking + none",
    label: "Designer",
    owner: "Sarah",
    date: "12 Oct 24",
    status: "Published",
    tool: ["World Tracking"],
    link: "https://example.com/project5",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_6.jpg",
    name: "3tool + mindfile",
    label: "Designer legacy",
    owner: "David",
    date: "20 Sep 24",
    status: "Unpublished",
    tool: ["Image Tracking", "Face Tracking", "World Tracking"],
    link: "https://example.com/project6",
  },
  {
    project_id: "4dce27a0-486c-4d87-a0b7-7c6b66dd210e",
    workspace_id: "1",
    user_id: "1",
    image: "/card_project/example_7.jpg",
    name: "3 tool none",
    label: "Designer legacy",
    owner: "Emily",
    date: "18 Sep 24",
    status: "Unpublished",
    tool: ["Image Tracking", "Face Tracking", "World Tracking"],
    link: "https://example.com/project7",
  },
];
