name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main # กำหนดให้ทำงานเมื่อมีการ push ไปที่ branch 'main' เท่านั้น

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # ใช้ Node.js เวอร์ชัน 20 ที่คุณใช้

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Production
        run: pnpm run build

      # --- ส่วนสำคัญ: SSH และ Deployment ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # คำสั่งทั้งหมดที่จะรันบน VPS ของคุณ
          script: |
            echo "Starting deployment on server..."
            cd /home/developer/wemear
            git pull origin main # 1. ดึงโค้ดล่าสุด

            pnpm install        # 2. ติดตั้ง dependencies 
            pnpm run build      # 3. Build Production (สร้างโฟลเดอร์ dist ใหม่)

            # 4. *** เพิ่ม: ยืนยันสิทธิ์การเดินผ่าน (Traverse) ให้กับ Nginx ***
            sudo chmod o+x /home/developer
            sudo chmod o+x /home/developer/wemear

            # 5. แก้ไขสิทธิ์ของโฟลเดอร์ dist ใหม่ทันที
            echo "Setting ownership and permissions for Nginx..."
            sudo chown -R www-data:www-data /home/developer/wemear/dist
            sudo chmod -R 755 /home/developer/wemear/dist

            # 6. รีโหลด Nginx
            sudo systemctl reload nginx
            echo "Deployment successful and Nginx reloaded."
