name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main # กำหนดให้ทำงานเมื่อมีการ push ไปที่ branch 'main' เท่านั้น

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      # --- ส่วนสำคัญ: SSH และ Deployment ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # คำสั่งทั้งหมดที่จะรันบน VPS ของคุณ
          script: |
            echo "Starting deployment on server, no dist_old rename."
            cd /home/developer/wemear

            # 1. ดึงโค้ดล่าสุดจาก GitHub
            git pull origin main 

            # 2. ติดตั้ง dependencies และ Build Production (สร้าง dist ใหม่)
            # โฟลเดอร์ dist เก่าจะถูกลบและสร้างใหม่โดย pnpm run build
            npm install        
            npm run build      

            # 3. *** จัดการสิทธิ์ทั้งหมด: แก้ปัญหา 500 Internal Server Error ***
            echo "Setting necessary directory and file permissions for Nginx..."

            # อนุญาตให้ www-data (Nginx) เดินผ่าน Home และ Project Directory ได้
            sudo chmod o+x /home/developer
            sudo chmod o+x /home/developer/wemear

            # เปลี่ยนเจ้าของโฟลเดอร์ dist ที่เพิ่งสร้างใหม่ทั้งหมด
            sudo chown -R www-data:www-data /home/developer/wemear/dist
            sudo chmod -R 755 /home/developer/wemear/dist

            # 4. รีโหลด Nginx เพื่อเสิร์ฟไฟล์ใหม่
            sudo systemctl reload nginx
            echo "Deployment successful and Nginx reloaded."
