name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main # กำหนดให้ทำงานเมื่อมีการ push ไปที่ branch 'main' เท่านั้น

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # เราจะรัน install บน Server แทน เพื่อให้มั่นใจว่า Environment ตรงกัน
      - name: Install dependencies locally (For runner to find pnpm)
        run: npm install -g pnpm && pnpm install

      # --- ส่วนสำคัญ: SSH และ Deployment ---
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # คำสั่งทั้งหมดที่จะรันบน VPS ของคุณ
          script: |
            echo "Starting deployment on server."
            cd /home/developer/wemear

            # 1. ดึงโค้ดล่าสุดจาก GitHub
            git pull origin main 

            # 2. *** สำคัญ: ติดตั้งและ Build โดยใช้ pnpm ***
            # *ต้องมั่นใจว่า pnpm ถูกติดตั้งบน Server แล้ว*
            pnpm install        # ติดตั้ง Dependencies ใหม่
            pnpm run build      # Build Production (สร้าง dist ใหม่)

            # 3. จัดการสิทธิ์ทั้งหมด (แก้ปัญหา 500 Internal Server Error)
            echo "Setting necessary directory and file permissions for Nginx..."

            # ยืนยันสิทธิ์การเดินผ่าน
            sudo chmod o+x /home/developer
            sudo chmod o+x /home/developer/wemear

            # เปลี่ยนเจ้าของโฟลเดอร์ dist ที่เพิ่งสร้างใหม่ทั้งหมด
            sudo chown -R www-data:www-data /home/developer/wemear/dist
            sudo chmod -R 755 /home/developer/wemear/dist

            # 4. รีโหลด Nginx เพื่อเสิร์ฟไฟล์ใหม่
            sudo systemctl reload nginx
            echo "Deployment successful and Nginx reloaded."
